404 Not found

diff --git a/.github/workflows/test-docker.yaml b/.github/workflows/test-docker.yaml
--- a/.github/workflows/test-docker.yaml
+++ b/.github/workflows/test-docker.yaml
@@ -15,10 +15,13 @@ jobs:
     steps:
       - name: Check if image manifest is available
         run: |
-          MANIFEST=$(curl -X GET https://${IMAGE}/manifests/$GITHUB_SHA -u $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }})
-          echo $MANIFEST
-          SHA_COUNT=$(echo $MANIFEST | grep -c "$GITHUB_SHA" || true)
-          echo "Found $SHA_COUNT mentions of current github sha"
+          MANIFEST=$(curl -I -X GET https://${IMAGE}/manifests/$GITHUB_SHA -u $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }})
+          echo "Github manifest statistics:
+          $MANIFEST
+          ----"
+
+          NF_COUNT=$(echo $MANIFEST | grep -c 404\ Not\ Found || true)
+          echo "Found $NF_COUNT mentions of 404 Not Found"
       - uses: actions/checkout@v2
       - uses: actions/setup-java@v1.3.0
         with:
