find cucumber.json from new folder

diff --git a/.github/workflows/test-cucumber-pages.yaml b/.github/workflows/test-cucumber-pages.yaml
--- a/.github/workflows/test-cucumber-pages.yaml
+++ b/.github/workflows/test-cucumber-pages.yaml
@@ -2,7 +2,7 @@ name: cucumber report
 on:
   push:
     branches:
-      - master
+      - feature/fix-cucumber-workflow
 
 jobs:
   report-page:
@@ -12,9 +12,9 @@ jobs:
     steps:
       - uses: actions/checkout@v2
       - name: passed
-        run: echo $(jq '.[].elements[].steps[].result.status' .github/resources/cucumber.json | grep -c passed || true) > passed
+        run: echo $(jq '.[].elements[].steps[].result.status' src/test/resources/cucumber.json | grep -c passed || true) > passed
       - name: failed
-        run: echo $(jq '.[].elements[].steps[].result.status' .github/resources/cucumber.json | grep -c failed || true) > failed
+        run: echo $(jq '.[].elements[].steps[].result.status' src/test/resources/cucumber.json | grep -c failed || true) > failed
       - uses: navikt/bidrag-gh-pages/cucumber-move@master
         with:
           folder_move_from: resources/generated-report
